create database customer_behavior;
use customer_behavior;

select *from customer;

#Q1. Toatal revenue generated by male and Female customers?
select gender, sum(purchase_amount) as  revenue
from customer
group by gender;

#Q2. Which customers uses a discount but still spend more than average purchase amount?
select customer_id, purchase_amount 
from customer
where discount_applied='Yes' and 
purchase_amount >= (select avg(purchase_amount) from customer);


#Q3. Top 5 products with highest average review rating 
 select	 item_purchased , round(avg(review_rating),2) as avg_review_rating 
 from customer
 group by item_purchased
 order by avg_review_rating desc
 limit 5;
 
 
 #Q4. compare average purchase amount between Express and statndard shipping
 select shipping_type, round(avg(purchase_amount),2) as avg_purchase_amount
 from customer
 where shipping_type in ('standard','express')
 group by shipping_type;
 
 

 #Q5. Do subscribrs customers spend more ? compare total revenue and average spend between subscribers and nun subscribers
 select subscription_status, count(distinct customer_id)  ,
 round(avg(purchase_amount),2) as avg_spend,
 round(sum(purchase_amount),2) as total_revenue
 from customer
 group by subscription_status
 order by total_revenue desc;
 
 #Q6. which 5 products have the highest percentage of purchases with discount applied ?
 
 select count(*) from customer;
 select item_purchased ,
 round(100* sum(case when discount_applied='Yes' then 1 else 0 end )/count(*),2) as discount_rate
 from customer
 group by item_purchased
 order by discount_rate desc
 limit 5;
 
 
 #Q7. Segent customers based on new ,returning , loyal based on their previous purchase and show 
 # the count of each segment 
 
with customer_type as 
(select	 customer_id, previous_purchases ,
case
  when previous_purchases =1 then 'New'
  when previous_purchases between 2 and 10 then 'Returning'
  else 'Loyal'
  end as customer_segment
  from customer)
select customer_segment , count(*) as number_of_customer 
from customer_type
group by customer_segment
order by number_of_customer desc;



#Q.8 top 3 item purchased per category 
with item_counts as 
(select item_purchased, category , count(customer_id) as total_order ,
row_number() over(partition by category order by count(customer_id) desc ) as item_rank
from customer
group by category , item_purchased )

select item_rank,  item_purchased, category, total_order
from item_counts
where item_rank <=3 ; 

  
  
#Q9. Number of repeating buyers ( more than 5 previous purchases ) compare with subscription status
select subscription_status ,count(customer_id) as number_of_customer
from customer
where previous_purchases >= 5
group by subscription_status ;

#Q10. what is the revenue contribution of each age group
select age_group, sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;

  
  
 


